FROM node:8.11.1-alpine

# DIRECTORY
WORKDIR /app

# COPYING DEPENDENCIES FILE TO WORKING DIRECTORY
COPY package*.json ./

# INSTALLING APP DEPENDENCIES
RUN npm install

# COPYING THE CURRENT CODE TO THE WORKING DIRECTORY
COPY . .

# EXPOSE THE APPLICATION ON PORT 3000
EXPOSE 3000

# RUNNING THE APPLICATION
CMD [ "node", "server.js" ]
